# Generated by Django 5.1.3 on 2025-01-15 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursosapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
