# Generated by Django 5.1.3 on 2025-01-16 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursosapp', '0002_alter_estudiante_fecha_nacimiento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estudiante',
            options={'verbose_name': 'Estudiante', 'verbose_name_plural': 'Estudiantes'},
        ),
    ]
